# Generated by Django 4.1 on 2022-08-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='owner',
            new_name='user',
        ),
    ]
