# Generated by Django 4.1 on 2022-08-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_owner_shoppinglist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='user',
            new_name='owner',
        ),
    ]
