# Generated by Django 4.1 on 2022-08-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_shoppinglist_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='owner',
            new_name='user',
        ),
    ]
